### ISSUE TITLE
(Brandow) - (Frontend) Implementar telas/componentes principais

### ISSUE THREAD

**Issue by yuryalencar** [yuryalencar/curupira-analysis#11]
Resultados:
* Implementar tela de login
* Escolher uma lib de gráficos boa (Suporte pra TS é legal se conseguirmos)
* Definir como o backend deve mandar os dados para montar o gráfico no FE. (O mais fácil possível para o FE)

Dúvidas que seriam legais serem respondidas:
* Mandamos separados por instituição ?
* Mandamos um compilado com todos ?
* Mandamos ambos ?

ps.: É interessante colocarmos um filtro por instituições e isso atualizar os gráficos. Então talvez mandar ambos seja legal. Mas temos que avaliar qual melhor formato.

**Comment by BrandowBuenos** [comment]
Modelo de dados para o gráfico Teses por Linguagem:

```json
{
  "data": [
    {
      "instituition": "PUC-MG-I-4",
      "portuguese": 1,
      "english": 0
    },
    {
      "instituition": "UFSCAR-CC-4",
      "portuguese": 36,
      "english": 0
    },
    {
      "instituition": "UFSCAR-CC-4",
      "portuguese": 37,
      "english": 2
    },
    {
      "instituition": "UFSCAR-CC-4",
      "portuguese": 31,
      "english": 3
    }
  ]
}
```

**Comment by BrandowBuenos** [comment]
Gráfico de modelo

![Screen Shot 2022-05-28 at 15 10 19](https://user-images.githubusercontent.com/52222495/171070415-aad59f00-3056-4210-85e1-fd69c7356beb.png)
