### ISSUE TITLE
(Brandow) - Organizar a arquitetura do FrontEnd.

### ISSUE THREAD

**Issue by yuryalencar** [yuryalencar/curupira-analysis#5]
Resultados: 
* Criar o Projeto
* Organizar a estrutura de pastas
* Abrir a PR

Ps.: Vamos utilizar NextJS + Atomic Design

**Comment by BrandowBuenos** [comment]
@yuryalencar @ThalisAntunesDaSilva , utilizaremos JS ou TS para. projeto ?
